Title
========================================================

```{r}
getwd()
```

Download the file
```{r}
fileUrl <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"

if (!file.exists("Dataset.zip")) {
    download.file(fileUrl, destfile = "Dataset.zip", method = "wget")
}
```

Unzip the file.

```{r}
if (!file.exists("household_power_consumption.txt")) {
    unzip("Dataset.zip", overwrite = TRUE)
}
```


```{r}
rm(list=ls())
```


Load Partial\Complete file
```{r}
#df  <-  read.table('household_power_consumption.txt',header=T,sep=";",na.strings="?",nrows=10)
df  <-  read.table('household_power_consumption.txt',header=T,sep=";",na.strings="?")
```

```{r}
colnames(df)
```

Convert date  to date classes using as.Date() function
```{r}

#df$Date; as.Date(df$Date,"%d/%m/%Y"); class(df$Date)
df$Date  <- as.Date(df$Date,"%d/%m/%Y"); class(df$Date)
```

dates for which the data is needed  2007-02-01 and 2007-02-02
```{r}
dates  <- c("2007-02-01","2007-02-02")
dates  <- as.Date(dates);dates
```

```{r}
identical(("2007-02-02"),as.character(as.Date("2007-02-02")))
```


Take Subset of the dataset

```{r}
df1  <- subset(df,Date %in% dates)
#rm(df)
```



```{r}
df1 <- within(df1, Datetime <- strptime(paste(as.character(df1$Date), df1$Time), format="%Y-%m-%d %H:%M:%S"));head(df1)

#paste(as.character(df$Date), df$Time)[1:10]
#strptime("2006-12-16 17:24:00", format = "%Y-%m-%d %H:%M:%S")

```




```{r}
df1[,c(1,3)]
plot(df1[,3])

hist(df1[,3],col = "red")



```


Graph 2
```{r}
plot(as.factor(df1$Datetime$wday),df1$Global_active_power,type = "b" )

```



```{r}
?hist

```



===============================================================================================================================
Get the values
```{r}
#unlist(unclass(df$Date))
```


http://stackoverflow.com/a/10708074/2356016
Works!!!
```{r}
rm(dt)
dt  <- strptime("16/12/2006 17:24:00", format="%d/%m/%Y %H:%M:%S")
dt
class(dt)
names(dt)
unlist(unclass(dt))
```


```{r}
dt  <- as.POSIXlt("16/12/2006 17:24:00", format="%d/%m/%Y %H:%M:%S")
rm(dt)
dt  <- as.POSIXlt("16/12/2006 17:24:00", format="%d/%m/%Y");dt



class(dt)
names(dt)

```




```{r}
paste(df$Date, df$Time)
```


```{r}
strptime(paste(df$Date, df$Time), format="%d/%m/%Y %H:%M:%S")
```

http://stackoverflow.com/a/5251189/2356016


```{r}
df <- within(df, Datetime <- strptime(paste(df$Date, df$Time), format="%d/%m/%Y %H:%M:%S"))
```


http://stats.stackexchange.com/q/3997

```{r}
#names(df$Datetime)
unlist(unclass(df$Datetime))
```

```{r}
df$Datetime
```


```{r}
df$Datetime$year 
```


```{r}
df$Datetime$year == 106 # Since 1990
```






You can also embed plots, for example:

```{r fig.width=7, fig.height=6}
plot(cars)
```







```{r}
z  <-  Sys.time()
z
class(z)
y  <- as.POSIXlt(z)
y  <- as.POSIXlt.Date(z)
y  <- as.POSIXlt.date(z)
y  <- as.POSIXlt.POSIXct(z)
y
class(y)
names(y)
```

